spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: ""
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://accounts.google.com/o/oauth2/token
            redirect-uri: http://localhost:8080/getUserSubscriptions