#  Documentation on OAuth 2 configuration here:
#  https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 187713709108-jisnv4kjvcfhrs4rngf6sbeiiqj97pct.apps.googleusercontent.com
            clientSecret: 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
            scope: openid,profile,email,https://www.googleapis.com/auth/youtube.readonly


logging:
  level:
    com.springbootlearning: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE